language: cpp
sudo: false
compiler: gcc

addons:
   apt: 
     packages:
          clang-3.4
          g++-4.8
          libbost-all-dev
          doxygen
          valgrind
          libgtest0
          libgtest-dev

before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++-4.8 --version 2>&1 | grep g++-4.8
    - gcov-4.6 --version | grep gcov
    - gcov-4.8 --version | grep gcov
    - valgrind --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version

script:
    - date
    - ls -al
    - make Collatz.log
    - make collatz-tests
    - ls -al
    - make html
    - ls -al
    - make test
    - make clean
    - make test CXX=clang++
    - ls -al
    - make check
