language: cpp
sudo: false
compiler: gcc
addons:
  apt: 
     packages:
       - clang
       - g++
       - doxygen
       - valgrind
       - libgtest-dev
       - cmake
          
before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++
    - gcov --version | grep gcov
    - valgrind --version
#    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version
    - mkdir ~/gtest
    - mkdir ~/build
    - cp /usr/src/gtest ~/gtest
    - cd ~/gtest
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=~/build ./
    - make
    - ln -s *.a ~/bin/
# copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
# sudo cp *.a /usr/lib
script:
    - ls -al
    - make Collatz.log
    - make collatz-tests
    - ls -al
    - make html
    - ls -al
    - make test
    - make clean
    - make test CXX=clang++
    - ls -al
    - make check
