sudo: false
addons:
  apt: 
     packages:
       - make
       - cmake
       - g++-4.8
       - gcc-4.8
       - clang
       - doxygen
       - valgrind
       - libgtest-dev
       - libboost-dev
 
before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++
    - gcov --version | grep gcov
    - valgrind --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version
    - mkdir ~/gtest
    - mkdir ~/build1
    - mkdir ~/lib
    - cp -r /usr/src/gtest/* ~/gtest/
    - cd ~/gtest
    - export CPATH=$(pwd)
    - export LIBRARY_PATH=$(pwd)
    - export PATH=$(pwd):$PATH
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=~/build1 ./
    - make
    - cp ./*.a ~/lib/
    - cd -
# copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
# sudo cp *.a /usr/lib
script:
    - ls -al
    - make Collatz.log
    - make collatz-tests
    - ls -al
    - make html
    - ls -al
    - make test
    - make clean
    - make test CXX=clang++
    - ls -al
    - make check
